In [1]:
str1 = "Karachi is one of the most congested city in the world."
str2 = "Karachi is the financial capital of Pakistan."
str3 = "Islamabad is the capital of Pakistan."

In [2]:
strlist = [str1,str2,str3]
print(strlist)

['Karachi is one of the most congested city in the world.', 'Karachi is the financial capital of Pakistan.', 'Islamabad is the capital of Pakistan.']


In [3]:
stopword = set("of the a is in".split())
print(stopword)

{'of', 'the', 'a', 'is', 'in'}


In [ ]:
str1.split()

In [5]:
s = []
for str in strlist: 
    s_list = [word for word in str.split() if word not in stopword]
    #print(s_list)
    str_ = ' '.join(s_list)   
    s.append(str_) 
print(s) 

['Karachi one most congested city world.', 'Karachi financial capital Pakistan.', 'Islamabad capital Pakistan.']


In [6]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
tfidf_vectorizer = TfidfVectorizer()                                                                    #Take 1/0 and compute its IDF and multiply each word wuth IDF --> IDF-DF
tfidf_vectorizer.fit(s)
print(tfidf_vectorizer.vocabulary_)

{'karachi': 5, 'one': 7, 'most': 6, 'congested': 2, 'city': 1, 'world': 9, 'financial': 3, 'capital': 0, 'pakistan': 8, 'islamabad': 4}


In [8]:
print(tfidf_vectorizer.get_feature_names())

['capital', 'city', 'congested', 'financial', 'islamabad', 'karachi', 'most', 'one', 'pakistan', 'world']


In [9]:
vec2 = tfidf_vectorizer.transform(s).toarray()
print(vec2.shape)

(3, 10)


In [10]:
print(vec2)

[[0.         0.42339448 0.42339448 0.         0.         0.32200242
  0.42339448 0.42339448 0.         0.42339448]
 [0.45985353 0.         0.         0.60465213 0.         0.45985353
  0.         0.         0.45985353 0.        ]
 [0.51785612 0.         0.         0.         0.68091856 0.
  0.         0.         0.51785612 0.        ]]


In [11]:
cs1 = cosine_similarity(vec2)                                                                               #Values different but result/analsis same as BoW
print(cs1)

[[1.         0.14807395 0.        ]
 [0.14807395 1.         0.47627592]
 [0.         0.47627592 1.        ]]


In [13]:
new_str = "Lahore is the second largest city of Pakistan and an important financial center."

n_list = [word for word in new_str.split() if word not in stopword]
new_str = ' '.join(n_list)

print(new_str)

Lahore second largest city Pakistan and an important financial center.


In [18]:
response2 = tfidf_vectorizer.transform([new_str])
print(response2)

  (0, 8)	0.4736296010332684
  (0, 3)	0.6227660078332259
  (0, 1)	0.6227660078332259


In [19]:
response2.toarray()

array([[0.        , 0.62276601, 0.        , 0.62276601, 0.        ,
        0.        , 0.        , 0.        , 0.4736296 , 0.        ]])

In [20]:
answer2 = cosine_similarity(response2,vec2)
print(answer2)

[[0.26367569 0.59435704 0.24527199]]


In [22]:
import numpy as np
ans2 = answer2[0]
print("the maximum is ", max(ans2))                                                                              #same result as BoW

b = np.argmax(ans2)
print(b, strlist[b]) 

the maximum is  0.5943570354323497
1 Karachi is the financial capital of Pakistan.
